// Auto-generated by extra/generate_device_config_widgets.py. Do not edit.
#ifndef GENERATED_DEVICE_CONFIG_WIDGETS_HPP
#define GENERATED_DEVICE_CONFIG_WIDGETS_HPP

#include <WiFi.h>
#include <Arduino.h>
#include <cstring>

#include "os/datacontainer/NvmConfigSlotDefinition.hpp"

namespace GeneratedDeviceConfigWidgets
{
struct FieldSpec
{
    const char* key;
    const char* label;
    const char* htmlType;
    uint8_t offset;
    uint8_t size;
    int minimum;
    int maximum;
    const char* optionValues[2];
    const char* optionLabels[2];
    uint8_t optionCount;
    uint8_t arrayLength;
};

struct DeviceTypeSpec
{
    uint8_t typeId;
    const char* label;
    const char* enumSymbol;
    FieldSpec fields[8];
    uint8_t fieldCount;
};

inline uint16_t readValue(const DeviceConfigSlotType& slot, const FieldSpec& field)
{
    uint16_t value = 0;
    const uint8_t readableSize = field.size > sizeof(value) ? sizeof(value) : field.size;
    memcpy(&value, &slot.customBytes[field.offset], readableSize);
    return value;
}

inline void emitSelect(uint8_t slotNumber, const FieldSpec& field, uint16_t value, WiFiClient& client)
{
    client.println("<label>" + String(field.label) + ":<select id=\"" + String(field.key) + "-" + String((int)slotNumber) + "\">");
    for (uint8_t option = 0; option < field.optionCount; ++option)
    {
        const bool selected = value == String(field.optionValues[option]).toInt();
        client.println(String("<option value=\"") + String(field.optionValues[option]) + "\"" + (selected ? " selected" : "") + ">" + String(field.optionLabels[option]) + "</option>");
    }
    client.println("</select></label>");
}

inline void emitGpioSelect(uint8_t slotNumber, const FieldSpec& field, uint16_t value, WiFiClient& client)
{
    client.println("<label>" + String(field.label) + ":<select id=\"" + String(field.key) + "-" + String((int)slotNumber) + "\">");
    for (uint8_t pin = 0; pin < 32; ++pin)
    {
        client.println(String("<option value=\"") + String((int)pin) + "\"" + (value == pin ? " selected" : "") + ">" + String((int)pin) + "</option>");
    }
    client.println("</select></label>");
}

inline void emitField(uint8_t slotNumber, const DeviceConfigSlotType& slot, const FieldSpec& field, WiFiClient& client)
{
    const uint16_t value = readValue(slot, field);
    const String htmlType = String(field.htmlType);
    if (htmlType == "select") { emitSelect(slotNumber, field, value, client); return; }
    if (htmlType == "gpio-select") { emitGpioSelect(slotNumber, field, value, client); return; }
    if (htmlType == "checkbox")
    {
        client.println(String("<label><input id=\"") + String(field.key) + "-" + String((int)slotNumber) + "\" type=\"checkbox\"" + (value ? " checked" : "") + "> " + String(field.label) + "</label>");
        return;
    }
    if (htmlType == "range" || htmlType == "number")
    {
        client.println("<label>" + String(field.label) + ":<input id=\"" + String(field.key) + "-" + String((int)slotNumber) + "\" type=\"" + htmlType + "\" min=\"" + String(field.minimum) + "\" max=\"" + String(field.maximum) + "\" value=\"" + String((int)value) + "\"></label>");
        return;
    }
    if (htmlType == "segment-array")
    {
        for (uint8_t index = 0; index < field.arrayLength; ++index)
        {
            client.println("<label><input id=\"seg" + String((int)(index + 1)) + "Count-" + String((int)slotNumber) + "\" type=\"number\" min=\"" + String(field.minimum) + "\" max=\"" + String(field.maximum) + "\" value=\"" + String((int)slot.customBytes[field.offset + index]) + "\">");
            const bool inverted = slot.customBytes[field.offset + field.arrayLength + index] != 0;
            client.println(String("<select id=\"Seg") + String((int)(index + 1)) + "Flip-" + String((int)slotNumber) + "\"><option value=\"0\"" + (inverted ? "" : " selected") + ">Not inversed</option><option value=\"1\"" + (inverted ? " selected" : "") + ">Inversed</option></select></label>");
        }
    }
}

inline const DeviceTypeSpec kKnownDeviceTypeWidgetSpecs[] = {
    {47, "DistanceSensor", "type_DISTANCE_SENSOR", {{"pinTx", "Pin Tx", "gpio-select", 2, 1, 0, 255, {"", ""}, {"", ""}, 0, 0},
        {"pinRx", "Pin Rx", "gpio-select", 3, 1, 0, 255, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0}}, 2},
    {44, "LedStrip", "type_LED_STRIP", {{"ledsCount", "LEDs num.", "number", 0, 2, 1, 255, {"", ""}, {"", ""}, 0, 0},
        {"ledsSideFlip", "Sides flip", "select", 2, 1, 0, 255, {"0", "1"}, {"Not inversed", "Inversed"}, 2, 0},
        {"curLim", "Current limiter", "range", 3, 1, 15, 254, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0}}, 3},
    {43, "OnOff", "type_ONOFFDEVICE", {{"brightnessSupported", "Brightness support", "select", 0, 1, 0, 255, {"0", "1"}, {"No", "Yes"}, 2, 0},
        {"activationState", "Active state", "select", 1, 1, 0, 255, {"0", "1"}, {"LOW (0)", "HIGH (1)"}, 2, 0},
        {"pwmMin", "Min PWM", "range", 2, 1, 0, 255, {"", ""}, {"", ""}, 0, 0},
        {"pwmMax", "Max PWM", "range", 3, 1, 0, 255, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0}}, 4},
    {46, "SegLedStrip", "type_LED_STRIP_SEGMENTED", {{"SegcurLimVal", "Current limiter", "range", 0, 1, 15, 254, {"", ""}, {"", ""}, 0, 0},
        {"segmentLedCounts", "Segment counts", "segment-array", 5, 5, 1, 100, {"", ""}, {"", ""}, 0, 5},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0}}, 2},
    {45, "TempSensor", "type_TEMP_SENSOR", {{"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0},
        {"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0}}, 0}
};

inline void emitTypeSelector(uint8_t slotNumber, uint8_t selectedType, WiFiClient& client)
{
    client.println("<label>Type: <select onchange=\"showExtraFields(this, 'device-" + String((int)slotNumber) + "');\" id=\"type" + String((int)slotNumber) + "\">");
    bool selected = false;
    for (const auto& spec : kKnownDeviceTypeWidgetSpecs)
    {
        const bool isSelected = spec.typeId == selectedType;
        selected = selected || isSelected;
        client.println(String("<option value=\"") + String((int)spec.typeId) + "\"" + (isSelected ? " selected" : "") + ">" + String(spec.label) + "</option>");
    }
    client.println(selected ? "<option value=\"255\">UNKNOWN</option>" : "<option value=\"255\" selected>UNKNOWN</option>");
    client.println("</select></label>");
}

inline void emitGeneratedCustomFields(uint8_t slotNumber, uint8_t deviceType, const DeviceConfigSlotType& slot, WiFiClient& client)
{
    for (const auto& spec : kKnownDeviceTypeWidgetSpecs)
    {
        client.println("<div class=\"extra-fields extra-" + String((int)spec.typeId) + "\">");
        for (uint8_t field = 0; field < spec.fieldCount; ++field) { emitField(slotNumber, slot, spec.fields[field], client); }
        client.println("</div>");
    }
}
}

#endif
