#!/usr/bin/env python3
"""@file
@brief Generate configuration-page HTML field metadata from device JSON descriptions.

Only registered, configurable device types are emitted. C++ build guards ensure the selector and
field containers match the implementations enabled in the current firmware profile.
"""

import json
from pathlib import Path

try:
    Import("env")
    PROJECT_DIR = Path(env["PROJECT_DIR"])
except NameError:
    PROJECT_DIR = Path(__file__).resolve().parent.parent
DEVICES_DIR = PROJECT_DIR / "include" / "devices"
OUTPUT_FILE = PROJECT_DIR / "include" / "generated" / "GeneratedDeviceConfigWidgets.hpp"


def cpp_string(value):
    return json.dumps(str(value))


def load_device_descriptions():
    descriptions = []
    for path in sorted(DEVICES_DIR.glob("*/*.json")):
        if path.name == "device.schema.json":
            continue

        with path.open(encoding="utf-8") as source:
            description = json.load(source)

        manager = description["implementation"]["manager"]
        http_config = description["deviceType"].get("httpConfig", {})
        if not (manager["registered"] and manager["includedInDeviceCollection"]):
            continue
        if not http_config.get("configurable", True):
            continue

        descriptions.append(description)

    return descriptions


def validate_field(path, field):
    if field.get("widget") is None:
        return

    required = ("label", "fieldId", "htmlType", "offset", "size")
    missing = [key for key in required if key not in field]
    if missing:
        raise ValueError(f"{path}: configuration field {field['name']!r} is missing {', '.join(missing)}")


def field_initializer(field):
    validate_field("device description", field)
    options = field.get("options", [])
    if len(options) > 2:
        raise ValueError(f"{field['name']}: the generated renderer supports at most two select options")

    option_values = [str(option["value"]) for option in options]
    option_labels = [option["label"] for option in options]
    option_values.extend([""] * (2 - len(option_values)))
    option_labels.extend([""] * (2 - len(option_labels)))
    return "{{{key}, {label}, {html_type}, {offset}, {size}, {minimum}, {maximum}, {{{option_values}}}, {{{option_labels}}}, {option_count}, {array_length}}}".format(
        key=cpp_string(field["fieldId"]),
        label=cpp_string(field["label"]),
        html_type=cpp_string(field["htmlType"]),
        offset=int(field["offset"]),
        size=int(field["size"]),
        minimum=int(field.get("minimum", 0)),
        maximum=int(field.get("maximum", 255)),
        option_values=", ".join(cpp_string(value) for value in option_values),
        option_labels=", ".join(cpp_string(value) for value in option_labels),
        option_count=len(options),
        array_length=int(field.get("arrayLength", 0)),
    )


def device_initializer(description):
    device_type = description["deviceType"]
    fields = [field for field in description["configuration"]["customBytes"] if field.get("widget") is not None]
    if len(fields) > 8:
        raise ValueError(f"{device_type['name']}: a generated device type supports at most eight configuration fields")

    fields.extend([None] * (8 - len(fields)))
    field_rows = [field_initializer(field) if field else '{"", "", "", 0, 0, 0, 0, {"", ""}, {"", ""}, 0, 0}' for field in fields]
    http_config = device_type.get("httpConfig", {})
    display_name = http_config.get("displayName", device_type["name"])
    initializer = "{{{type_id}, {name}, {enum_symbol}, {{{fields}}}, {field_count}}}".format(
        type_id=int(device_type["enumValue"]),
        name=cpp_string(display_name),
        enum_symbol=cpp_string(device_type["enumSymbol"]),
        fields=",\n        ".join(field_rows),
        field_count=sum(field is not None for field in fields),
    )
    build_guard = description["implementation"].get("buildGuard")
    if build_guard:
        return f"#ifdef {build_guard}\n    {initializer},\n    #endif"
    return initializer + ","


HEADER_TEMPLATE = r'''// Auto-generated by extra/generate_device_config_widgets.py. Do not edit.
/**
 * @file GeneratedDeviceConfigWidgets.hpp
 * @brief Schema-derived configuration-page controls for enabled device types.
 */
#ifndef GENERATED_DEVICE_CONFIG_WIDGETS_HPP
#define GENERATED_DEVICE_CONFIG_WIDGETS_HPP

#include <WiFi.h>
#include <Arduino.h>
#include <cstring>

#include "SystemDefinition.hpp"
#include "os/datacontainer/NvmConfigSlotDefinition.hpp"

namespace GeneratedDeviceConfigWidgets
{
/** @brief Rendering and byte-layout metadata for one configuration field. */
struct FieldSpec
{
    const char* key;
    const char* label;
    const char* htmlType;
    uint8_t offset;
    uint8_t size;
    int minimum;
    int maximum;
    const char* optionValues[2];
    const char* optionLabels[2];
    uint8_t optionCount;
    uint8_t arrayLength;
};

/** @brief Configuration widget metadata for one enabled device type. */
struct DeviceTypeSpec
{
    uint8_t typeId;
    const char* label;
    const char* enumSymbol;
    FieldSpec fields[8];
    uint8_t fieldCount;
};

inline uint16_t readValue(const DeviceConfigSlotType& slot, const FieldSpec& field)
{
    uint16_t value = 0;
    const uint8_t readableSize = field.size > sizeof(value) ? sizeof(value) : field.size;
    memcpy(&value, &slot.customBytes[field.offset], readableSize);
    return value;
}

inline void emitSelect(uint8_t slotNumber, const FieldSpec& field, uint16_t value, WiFiClient& client)
{
    client.println("<label>" + String(field.label) + ":<select id=\"" + String(field.key) + "-" + String((int)slotNumber) + "\">");
    for (uint8_t option = 0; option < field.optionCount; ++option)
    {
        const bool selected = value == String(field.optionValues[option]).toInt();
        client.println(String("<option value=\"") + String(field.optionValues[option]) + "\"" + (selected ? " selected" : "") + ">" + String(field.optionLabels[option]) + "</option>");
    }
    client.println("</select></label>");
}

inline void emitGpioSelect(uint8_t slotNumber, const FieldSpec& field, uint16_t value, WiFiClient& client)
{
    client.println("<label>" + String(field.label) + ":<select id=\"" + String(field.key) + "-" + String((int)slotNumber) + "\">");
    for (uint8_t pin = 0; pin < 32; ++pin)
    {
        client.println(String("<option value=\"") + String((int)pin) + "\"" + (value == pin ? " selected" : "") + ">" + String((int)pin) + "</option>");
    }
    client.println("</select></label>");
}

inline void emitField(uint8_t slotNumber, const DeviceConfigSlotType& slot, const FieldSpec& field, WiFiClient& client)
{
    const uint16_t value = readValue(slot, field);
    const String htmlType = String(field.htmlType);
    if (htmlType == "select") { emitSelect(slotNumber, field, value, client); return; }
    if (htmlType == "gpio-select") { emitGpioSelect(slotNumber, field, value, client); return; }
    if (htmlType == "checkbox")
    {
        client.println(String("<label><input id=\"") + String(field.key) + "-" + String((int)slotNumber) + "\" type=\"checkbox\"" + (value ? " checked" : "") + "> " + String(field.label) + "</label>");
        return;
    }
    if (htmlType == "range" || htmlType == "number")
    {
        client.println("<label>" + String(field.label) + ":<input id=\"" + String(field.key) + "-" + String((int)slotNumber) + "\" type=\"" + htmlType + "\" min=\"" + String(field.minimum) + "\" max=\"" + String(field.maximum) + "\" value=\"" + String((int)value) + "\"></label>");
        return;
    }
    if (htmlType == "segment-array")
    {
        for (uint8_t index = 0; index < field.arrayLength; ++index)
        {
            client.println("<label><input id=\"seg" + String((int)(index + 1)) + "Count-" + String((int)slotNumber) + "\" type=\"number\" min=\"" + String(field.minimum) + "\" max=\"" + String(field.maximum) + "\" value=\"" + String((int)slot.customBytes[field.offset + index]) + "\">");
            const bool inverted = slot.customBytes[field.offset + field.arrayLength + index] != 0;
            client.println(String("<select id=\"Seg") + String((int)(index + 1)) + "Flip-" + String((int)slotNumber) + "\"><option value=\"0\"" + (inverted ? "" : " selected") + ">Not inversed</option><option value=\"1\"" + (inverted ? " selected" : "") + ">Inversed</option></select></label>");
        }
    }
}

inline const DeviceTypeSpec kKnownDeviceTypeWidgetSpecs[] = {
    {{DEVICE_SPECS}}
};

/** @brief Emits the device type selector for one NVM configuration slot. */
inline void emitTypeSelector(uint8_t slotNumber, uint8_t selectedType, WiFiClient& client)
{
    client.println("<label>Type: <select onchange=\"showExtraFields(this, 'device-" + String((int)slotNumber) + "');\" id=\"type" + String((int)slotNumber) + "\">");
    bool selected = false;
    for (const auto& spec : kKnownDeviceTypeWidgetSpecs)
    {
        const bool isSelected = spec.typeId == selectedType;
        selected = selected || isSelected;
        client.println(String("<option value=\"") + String((int)spec.typeId) + "\"" + (isSelected ? " selected" : "") + ">" + String(spec.label) + "</option>");
    }
    client.println(selected ? "<option value=\"255\">UNKNOWN</option>" : "<option value=\"255\" selected>UNKNOWN</option>");
    client.println("</select></label>");
}

/** @brief Emits every generated type-specific field container for a configuration slot. */
inline void emitGeneratedCustomFields(uint8_t slotNumber, uint8_t deviceType, const DeviceConfigSlotType& slot, WiFiClient& client)
{
    for (const auto& spec : kKnownDeviceTypeWidgetSpecs)
    {
        client.println("<div class=\"extra-fields extra-" + String((int)spec.typeId) + "\">");
        for (uint8_t field = 0; field < spec.fieldCount; ++field) { emitField(slotNumber, slot, spec.fields[field], client); }
        client.println("</div>");
    }
}
}

#endif
'''


def generate():
    descriptions = load_device_descriptions()
    if not descriptions:
        OUTPUT_FILE.unlink(missing_ok=True)
        print("No configurable device descriptions; no configuration widgets generated")
        return
    specs = "\n    ".join(device_initializer(description) for description in descriptions)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(
        HEADER_TEMPLATE.replace("{{DEVICE_COUNT}}", str(len(descriptions))).replace("{{DEVICE_SPECS}}", specs),
        encoding="utf-8",
    )
    print(f"Generated {OUTPUT_FILE} from {len(descriptions)} device descriptions")


generate()