#ifndef NOTIFICATION_HANDLER_H
#define NOTIFICATION_HANDLER_H
#include <Arduino.h>
#include <os/datacontainer/DataContainer.hpp>
#include <queue>

#define MAX_NUMBER_OF_NOTIFICATIONS 10
/**
 * @class NotificationHandler
 * @brief Stores and serves UI notifications generated by the OS.
 *
 * The handler keeps a bounded queue of user-facing notifications, enriches new entries with the
 * current timestamp when possible, and exposes the oldest pending notification to the UI layer.
 */

class NotificationHandler {
    /**
     * FIFO queue of pending UI notifications waiting to be displayed or processed.
     */
    static std::queue<UserInterfaceNotification> notifications;

public:
    /**
     * Registers the notification callbacks in the system data container and initializes the queue.
     */
    static void init();

    /**
     * Keeps the handler ready for future calls. The implementation currently has no periodic work.
     */
    static void cyclic();

    /**
     * Clears any runtime state created by the notification manager.
     */
    static void deinit();

    /**
     * Adds a new notification to the queue, attaching the current timestamp when the system clock is available.
     * @param newNotification Notification object that should be stored and later displayed.
     * @return true when the notification was accepted; false when the queue is full.
     */
    static bool createNotification(UserInterfaceNotification& newNotification);

    /**
     * Returns the number of pending notifications currently stored in the queue.
     * @return Number of active notifications.
     */
    static uint8_t getActiveNotificationsCount();

    /**
     * Returns and removes the oldest notification from the queue.
     * @return The oldest pending notification; an empty/default object when no notification is available.
     */
    static UserInterfaceNotification getOldestNotification();

};

#endif