#ifndef NOTIFICATION_HANDLER_H
#define NOTIFICATION_HANDLER_H
#include <Arduino.h>
#include <os/datacontainer/DataContainer.hpp>
#include <deque>
#include <cstdint>

#define MAX_NUMBER_OF_NOTIFICATIONS 10
/**
 * @class NotificationHandler
 * @brief Stores and serves UI notifications generated by the OS.
 *
 * The handler keeps a bounded queue of user-facing notifications, enriches new entries with the
 * current timestamp when possible, and exposes the oldest pending notification to the UI layer.
 */

class NotificationHandler {
    struct PendingNotification {
        UserInterfaceNotification notification;
        uint32_t createdAtMs;
        uint32_t timeoutMs;
    };

    /**
     * FIFO queue of pending UI notifications waiting to be displayed or processed.
     */
    static std::deque<PendingNotification> notifications;

    static void removeExpiredNotifications();

public:
    static constexpr uint32_t DEFAULT_NOTIFICATION_TIMEOUT_MS = 60UL * 60UL * 1000UL;

    /**
     * Registers the notification callbacks in the system data container and initializes the queue.
     */
    static void init();

    /**
    * Removes notifications whose display timeout has elapsed.
     */
    static void cyclic();

    /**
     * Clears any runtime state created by the notification manager.
     */
    static void deinit();

    /**
     * Adds a new notification to the queue, attaching the current timestamp when the system clock is available.
     * @param newNotification Notification object that should be stored and later displayed.
     * @return true when the notification was accepted; false when the queue is full.
     */
    static bool createNotification(UserInterfaceNotification& newNotification);

    /**
     * Adds a new notification with a caller-defined display timeout.
     * @param newNotification Notification object that should be stored and later displayed.
     * @param timeoutMs Time in milliseconds for which the notification remains available.
     * @return true when the notification was accepted; false when the queue is full.
     */
    static bool createNotification(UserInterfaceNotification& newNotification, uint32_t timeoutMs);

    /**
     * Returns the number of pending notifications currently stored in the queue.
     * @return Number of active notifications.
     */
    static uint8_t getActiveNotificationsCount();

    /**
     * Returns and removes the oldest notification from the queue.
     * @return The oldest pending notification; an empty/default object when no notification is available.
     */
    static UserInterfaceNotification getOldestNotification();

};

#endif