#ifndef SYSTEM_DEFINITION_H
#define SYSTEM_DEFINITION_H

#define HAS_RF_RECEIVER

#define LED_STRIP_SUPPORTED
#define ON_OFF_SUPPORTED
#define TEMP_SENSOR_SUPPORTED
#define DISTANCE_SENSOR_SUPPORTED


#endif